# LABELS = [
#     "person",
#     "bicycle",
#     "car",
#     "motorcycle",
#     "airplane",
#     "bus",
#     "train",
#     "truck",
#     "boat",
#     "traffic light",
#     "fire hydrant",
#     "stop sign",
#     "parking meter",
#     "bench",
#     "bird",
#     "cat",
#     "dog",
#     "horse",
#     "sheep",
#     "cow",
#     "elephant",
#     "bear",
#     "zebra",
#     "giraffe",
#     "backpack",
#     "umbrella",
#     "handbag",
#     "tie",
#     "suitcase",
#     "frisbee",
#     "skis",
#     "snowboard",
#     "sports ball",
#     "kite",
#     "baseball bat",
#     "baseball glove",
#     "skateboard",
#     "surfboard",
#     "tennis racket",
#     "bottle",
#     "wine glass",
#     "cup",
#     "fork",
#     "knife",
#     "spoon",
#     "bowl",
#     "banana",
#     "apple",
#     "sandwich",
#     "orange",
#     "broccoli",
#     "carrot",
#     "hot dog",
#     "pizza",
#     "donut",
#     "cake",
#     "chair",
#     "couch",
#     "potted plant",
#     "bed",
#     "dining table",
#     "toilet",
#     "tv",
#     "laptop",
#     "mouse",
#     "remote",
#     "keyboard",
#     "cell phone",
#     "microwave",
#     "oven",
#     "toaster",
#     "sink",
#     "refrigerator",
#     "book",
#     "clock",
#     "vase",
#     "scissors",
#     "teddy bear",
#     "hair drier",
#     "toothbrush",
# ]

# LABELS = [
#     'blended_pepper', 
#     'blended_tomatoes_pepper', 
#     'crushed_garlic', 
#     'crushed_ginger', 
#     'cube_maggie', 
#     'curry_powder', 
#     'flesh_pepper', 
#     'fresh_garlic', 
#     'fresh_ginger', 
#     'fresh_onions', 
#     'fresh_orange_pepper', 
#     'fresh_red_pepper', 
#     'fresh_tomatoes', 
#     'garlic_powder', 
#     'maggie_open', 
#     'oil', 
#     'raw_rice', 
#     'salt', 
#     'slice_tomatoes', 
#     'sliced_ginger', 
#     'sliced_green_pepper', 
#     'sliced_onions', 
#     'sliced_orange_pepper', 
#     'sliced_pepper', 
#     'sliced_red_pepper'
# ]


LABELS = [
    'blended_pepper', 
    'blended_tomatoes_pepper', 
    'cooking_pot', 
    'curry_powder', 
    'garlic_powder', 
    'maggie_open', 
    'oil', 
    'raw_rice', 
    'salt', 
    'sliced_onions', 
    'spatula', 
    'water'
]